### ISSUE TITLE
Allow for link/emoji to be placed on next line

### ISSUE THREAD

**Issue by tannerlinsley** [strdr4605/jump2header#16]
## Description (Motivation)

I also use the `doctoc` package to generate table of contents and want it to work well with that library. For that to happen, `jump2header` can not overwrite the header contents themselves or doctoc will rebuild the TOC with the emoji in the link.

## Possible solution

Add an option that supports placing the emoji on the next line, or even better, get with doctoc and figure out a way for both libs to cowrite to the readme

## Expected result

```md

# Table of Contents

- [My Header](#my-header)


# My Header
[⬆️](#table-of-contents)

```

### TODO

- [ ] Implement feature
- [ ] Add unit test
- [ ] Add usage and describe in README

**Comment by strdr4605** [comment]
I had a request about adding the link at the end of the section with a text instead of emoji, like [here](https://github.com/OleksiyRudenko/a-tiny-JS-world#credits).

```md
# Table of Contents

- [My Header](#my-header)


# My Header

Some text

[Up to TOC](#table-of-contents)
```

What do you think about this solution?

1. The link at the end of section
2. Custom text or generated text: `Back To <header name>`

**Comment by tannerlinsley** [comment]
I like that idea, especially the custom text, but I would prefer both options ideally

**Comment by strdr4605** [comment]
I will try to add these features in the next days and then will close the issue, try generating links and if there are problems comment and/or reopen this issue!
